"""Add joystream forum category, thread, post and relationships

Revision ID: bf2fd52d3716
Revises: a2fc0a403498
Create Date: 2019-11-28 19:09:18.130954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf2fd52d3716'
down_revision = 'a2fc0a403498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('joystream_forum_category',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('created_at_block_number', sa.Integer(), nullable=True),
    sa.Column('created_at_moment', sa.BigInteger(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('num_direct_subcategories', sa.Integer(), nullable=True),
    sa.Column('num_direct_unmoderated_threads', sa.Integer(), nullable=True),
    sa.Column('num_direct_moderated_threads', sa.Integer(), nullable=True),
    sa.Column('position_in_parent_category', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.String(length=64), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('extrinsic_idx', sa.Integer(), nullable=True),
    sa.Column('event_idx', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'block_id')
    )
    op.create_index(op.f('ix_joystream_forum_category_block_id'), 'joystream_forum_category', ['block_id'], unique=False)
    op.create_index(op.f('ix_joystream_forum_category_description'), 'joystream_forum_category', ['description'], unique=False)
    op.create_index(op.f('ix_joystream_forum_category_id'), 'joystream_forum_category', ['id'], unique=False)
    op.create_index(op.f('ix_joystream_forum_category_parent_id'), 'joystream_forum_category', ['parent_id'], unique=False)
    op.create_index(op.f('ix_joystream_forum_category_title'), 'joystream_forum_category', ['title'], unique=False)
    op.create_table('joystream_forum_moderation_action',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('moderator_id', sa.String(length=64), nullable=True),
    sa.Column('moderated_at_block_number', sa.Integer(), nullable=True),
    sa.Column('moderated_at_moment', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_joystream_forum_moderation_action_id'), 'joystream_forum_moderation_action', ['id'], unique=False)
    op.create_table('joystream_forum_moderation_rationale',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('moderation_action_id', sa.BigInteger(), nullable=True),
    sa.Column('rationale', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['moderation_action_id'], ['joystream_forum_moderation_action.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_joystream_forum_moderation_rationale_id'), 'joystream_forum_moderation_rationale', ['id'], unique=False)
    op.create_table('joystream_forum_thread',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('nr_in_category', sa.Integer(), nullable=True),
    sa.Column('num_unmoderated_posts', sa.Integer(), nullable=True),
    sa.Column('num_moderated_posts', sa.Integer(), nullable=True),
    sa.Column('created_at_block_number', sa.Integer(), nullable=True),
    sa.Column('created_at_moment', sa.BigInteger(), nullable=True),
    sa.Column('author_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['joystream_forum_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_joystream_forum_thread_id'), 'joystream_forum_thread', ['id'], unique=False)
    op.create_index(op.f('ix_joystream_forum_thread_title'), 'joystream_forum_thread', ['title'], unique=False)
    op.create_table('joystream_forum_post',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.BigInteger(), nullable=True),
    sa.Column('nr_in_thread', sa.Integer(), nullable=True),
    sa.Column('current_text', sa.Text(), nullable=True),
    sa.Column('created_at_block_number', sa.Integer(), nullable=True),
    sa.Column('created_at_moment', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['joystream_forum_thread.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_joystream_forum_post_id'), 'joystream_forum_post', ['id'], unique=False)
    op.create_table('joystream_forum_thread_moderation',
    sa.Column('thread_id', sa.BigInteger(), nullable=True),
    sa.Column('moderation_action_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['moderation_action_id'], ['joystream_forum_moderation_action.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['joystream_forum_thread.id'], )
    )
    op.create_table('joystream_forum_post_moderation',
    sa.Column('post_id', sa.BigInteger(), nullable=True),
    sa.Column('moderation_action_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['moderation_action_id'], ['joystream_forum_moderation_action.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['joystream_forum_post.id'], )
    )
    op.create_table('joystream_forum_post_text_change_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('expired_at_block_number', sa.Integer(), nullable=True),
    sa.Column('expired_at_moment', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('post_id', sa.BigInteger(), nullable=True),
    sa.Column('author_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['joystream_forum_post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_joystream_forum_post_text_change_history_id'), 'joystream_forum_post_text_change_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_joystream_forum_post_text_change_history_id'), table_name='joystream_forum_post_text_change_history')
    op.drop_table('joystream_forum_post_text_change_history')
    op.drop_table('joystream_forum_post_moderation')
    op.drop_table('joystream_forum_thread_moderation')
    op.drop_index(op.f('ix_joystream_forum_post_id'), table_name='joystream_forum_post')
    op.drop_table('joystream_forum_post')
    op.drop_index(op.f('ix_joystream_forum_thread_title'), table_name='joystream_forum_thread')
    op.drop_index(op.f('ix_joystream_forum_thread_id'), table_name='joystream_forum_thread')
    op.drop_table('joystream_forum_thread')
    op.drop_index(op.f('ix_joystream_forum_moderation_rationale_id'), table_name='joystream_forum_moderation_rationale')
    op.drop_table('joystream_forum_moderation_rationale')
    op.drop_index(op.f('ix_joystream_forum_moderation_action_id'), table_name='joystream_forum_moderation_action')
    op.drop_table('joystream_forum_moderation_action')
    op.drop_index(op.f('ix_joystream_forum_category_title'), table_name='joystream_forum_category')
    op.drop_index(op.f('ix_joystream_forum_category_parent_id'), table_name='joystream_forum_category')
    op.drop_index(op.f('ix_joystream_forum_category_id'), table_name='joystream_forum_category')
    op.drop_index(op.f('ix_joystream_forum_category_description'), table_name='joystream_forum_category')
    op.drop_index(op.f('ix_joystream_forum_category_block_id'), table_name='joystream_forum_category')
    op.drop_table('joystream_forum_category')
    # ### end Alembic commands ###
